key_pair_name = "ec2_key"
environment   = "dev"
bucket_name   = "dev-portrait-data-engineer-bucket-20250427"
project_name  = "dev-portrait-data-engineer"
aws_region    = "us-east-1"
instance_type = "t3.medium"
