name: Code Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        cd ~/.ssh/
        echo "${{ secrets.EC2_SSH_KEY }}" >> id_ed25519
        echo "id_ed25519 created"
        chmod 600 ~/.ssh/id_ed25519
        echo "id_ed25519 given permissions"
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Pull Code and Restart Services
      run: |
        ssh -tt ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOT'
          cd /home/ubuntu/portrait-data-engineer-test
          git pull origin main
          cd docker
          docker-compose down
          docker-compose up -d
        EOT